export const TECHNICAL_AREAS = [
  { value: 'BACKEND', label: 'Backend' },
  { value: 'BUSINESS_ANALYSIS', label: 'Business Analysis' },
  { value: 'CLOUD_ENGINEER', label: 'Cloud Engineer' },
  { value: 'DATA_SCIENCE', label: 'Data Science' },
  { value: 'DATA_ENGINEERING', label: 'Data Engineering' },
  { value: 'DEVOPS', label: 'DevOps' },
  { value: 'DISTRIBUTED_SYSTEMS', label: 'Distributed Systems' },
  { value: 'ENG_MANAGEMENT', label: 'Engineering Management' },
  { value: 'FRONTEND', label: 'Frontend' },
  { value: 'FULLSTACK', label: 'Fullstack' },
  { value: 'MACHINE_LEARNING', label: 'Machine Learning' },
  { value: 'MOBILE_ANDROID', label: 'Mobile Android' },
  { value: 'MOBILE_IOS', label: 'Mobile iOS' },
  { value: 'OTHER', label: 'Other' },
  { value: 'PROD_MANAGEMENT', label: 'Product Management' },
  { value: 'PROJ_MANAGEMENT', label: 'Project Management' },
  { value: 'QA', label: 'Quality Assurance' },
];
