spring:
  config:
    activate:
      on-profile: flyio


  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    # Safety: do not allow clean in this profile
    clean-disabled: true

logging:
  level:
    org.springframework.jdbc: INFO
    org.flywaydb: INFO

# Use local storage instead of Google Drive on Fly.io by default
storage:
  type: local
  folders:
    main-folder: main
    resources-folder: resources
    events-folder: events
    mentors-folder: mentors
    mentors-profile-folder: mentors-profile
    images-folder: images

file:
  storage:
    # Fly.io has an ephemeral filesystem. Use /data which can be attached as a volume in fly.toml
    directory: /data

security:
  enabled: true