export const PATHS = {
  ABOUT_US_PAGE: '/api/cms/v1/about',
  CELEBRATE_HER_PAGE: '/api/cms/v1/celebrateHer',
  CODE_OF_CONDUCT: '/api/cms/v1/code-of-conduct',
  COLLABORATORS: '/api/cms/v1/collaborators',
  EVENTS_PAGE: '/api/cms/v1/events',
  EVENTS_FILTERS: '/api/cms/v1/events/filters',
  FOOTER_PAGE: '/api/cms/v1/footer',
  LANDING_PAGE: '/api/cms/v1/landingPage',
  MENTORSHIP_CODE_OF_CONDUCT: '/api/cms/v1/mentorship/code-of-conduct',
  MENTORSHIP_FAQ: '/api/cms/v1/mentorship/faq',
  MENTORSHIP_OVERVIEW: '/api/cms/v1/mentorship/overview',
  PARTNERS_PAGE: '/api/cms/v1/partners',
  TEAM_PAGE: '/api/cms/v1/team',
};
