name: reviewdog
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.CHECSTYLE_TOKEN }}
          issue-message: "Thank you for contribute by creating an issue"
          pr-message: "Thank you for contribute with your first pull request"
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Debug Info
        run:
          echo "Permissions: ${{ toJson(github.event) }}"
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.CHECSTYLE_TOKEN }}
          reporter: github-pr-review
          checkstyle_config: google_checks.xml
          fail_on_error: true
