name: reviewdog
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    env: 
      $REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
        with:
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          reporter: github-pr-review
          checkstyle_config: google_checks.xml
          fail_on_error: true
