name: reviewdog

on: [ pull_request, workflow_dispatch ]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.PAT_TOKEN_ADRIANA }}
          run: |
            curl -X POST \
            -H "Authorization: token ${REVIEWDOG_GITHUB_API_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            URL \
            -d '{"body": "a review", "event": "COMMENT"}'
        with:
          github_token: ${{ secrets.PAT_TOKEN_ADRIANA }}
          reporter: github-pr-check
