#name: reviewdog
#
#on: [ pull_request, workflow_dispatch ]
#jobs:
#  checkstyle:
#    name: runner / checkstyle
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: dbelyaev/action-checkstyle@master
#        with:
#          github_token: ${{ secrets.PAT_TOKEN }}
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.PAT_TOKEN }}
#          reporter: github-pr-review
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.PAT_TOKEN }}

name: reviewdog checks
on: [ pull_request, workflow_dispatch ]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@master
        id: checkstyle
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          reporter: github-pr-review

      - name: Set up Reviewdog
        run: echo "REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.PAT_TOKEN }}" >> $GITHUB_ENV

      - name: Run Reviewdog
        uses: reviewdog/reviewdog-action@v1
        with:
          name: reviewdog
          reporter: github-pr-review
          filter_mode: added
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}