name: reviewdog

on: [ pull_request ]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.PAT_TOKEN_ADRIANA }}
          reporter: github-pr-check