name: reviewdog

on: [ pull_request, workflow_dispatch ]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.PAT_TOKEN }}
          reporter: github-pr-review